### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by teenyhop** [teenyhop/sculptrust#1]
- [ ] Create a minimalistic shaping library using [`freetype`](https://docs.rs/crate/freetype-rs/0.11.0) backend.
- [ ] Try out various front-ends including Cairo and OpenGL.
- [ ] Define `Font` trait that can be used to generate glyphs from id.
- [ ] Define `Renderer` trait that can be used to render those glyphs?

Interesting crates:
- [font and opentype](https://bodoni.github.io/font/font/index.html)
- [font-atlas](https://github.com/TyOverby/font-atlas)
